require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DashboardsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dashboard. As you add validations to Dashboard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { domain: 'http://example.com', board_id: '123', name: 'Some Board' }
  }

  let(:invalid_attributes) {
    { domain: '', board_id: '', name: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DashboardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let!(:dashboard) { create(:dashboard) }

  describe "GET #index" do
    it "assigns all dashboards as @dashboards" do
      get :index, {}, valid_session
      expect(assigns(:dashboards)).to eq([dashboard])
    end
  end

  # describe "GET #epics" do
  #   let!(:issue) { create(:issue, dashboard: dashboard) }
  #   let!(:second_epic) { create(:issue, :completed, issue_type: 'Epic', dashboard: dashboard) }
  #   let!(:first_epic) { create(:issue, issue_type: 'Epic', dashboard: dashboard, completed: second_epic.completed - 1.day) }
  #
  #   it "assigns all the epics as @issues and orders them by completion date" do
  #     get :epics, {:id => dashboard.to_param, :format => :json}, valid_session
  #     expect(assigns(:issues)).to eq([first_epic, second_epic])
  #   end
  # end
  #
  # describe "GET #wip_histories" do
  #   let!(:issue) { create(:issue, :started, dashboard: dashboard) }
  #   let!(:wip_history) { WipHistory.create(date: issue.started, issue: issue) }
  #
  #   it "assigns the history to @wip_histories" do
  #     get :wip_histories, {:id => dashboard.to_param, :format => :json}, valid_session
  #     expect(assigns(:wip_histories)).to eq([wip_history])
  #   end
  # end

  describe "GET #show" do
    it "assigns the requested dashboard as @dashboard" do
      get :show, {:id => dashboard.to_param}, valid_session
      expect(assigns(:dashboard)).to eq(dashboard)
    end
  end

  describe "GET #new" do
    it "assigns a new dashboard as @dashboard" do
      get :new, {}, valid_session
      expect(assigns(:dashboard)).to be_a_new(Dashboard)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dashboard as @dashboard" do
      get :edit, {:id => dashboard.to_param}, valid_session
      expect(assigns(:dashboard)).to eq(dashboard)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Dashboard" do
        expect {
          post :create, {:dashboard => valid_attributes}, valid_session
        }.to change(Dashboard, :count).by(1)
      end

      it "assigns a newly created dashboard as @dashboard" do
        post :create, {:dashboard => valid_attributes}, valid_session
        expect(assigns(:dashboard)).to be_a(Dashboard)
        expect(assigns(:dashboard)).to be_persisted
      end

      it "redirects to the created dashboard" do
        post :create, {:dashboard => valid_attributes}, valid_session
        expect(response).to redirect_to(Dashboard.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dashboard as @dashboard" do
        post :create, {:dashboard => invalid_attributes}, valid_session
        expect(assigns(:dashboard)).to be_a_new(Dashboard)
      end

      it "re-renders the 'new' template" do
        post :create, {:dashboard => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'Another Board' }
      }

      it "updates the requested dashboard" do
        put :update, {:id => dashboard.to_param, :dashboard => new_attributes}, valid_session

        dashboard.reload
        expect(dashboard.name).to eq(new_attributes[:name])
      end

      it "assigns the requested dashboard as @dashboard" do
        put :update, {:id => dashboard.to_param, :dashboard => valid_attributes}, valid_session
        expect(assigns(:dashboard)).to eq(dashboard)
      end

      it "redirects to the dashboard" do
        put :update, {:id => dashboard.to_param, :dashboard => valid_attributes}, valid_session
        expect(response).to redirect_to(dashboard)
      end
    end

    context "with invalid params" do
      it "assigns the dashboard as @dashboard" do
        put :update, {:id => dashboard.to_param, :dashboard => invalid_attributes}, valid_session
        expect(assigns(:dashboard)).to eq(dashboard)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => dashboard.to_param, :dashboard => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dashboard" do
      expect {
        delete :destroy, {:id => dashboard.to_param}, valid_session
      }.to change(Dashboard, :count).by(-1)
    end

    it "redirects to the dashboards list" do
      delete :destroy, {:id => dashboard.to_param}, valid_session
      expect(response).to redirect_to(dashboards_url)
    end
  end

  describe "POST #sync" do
  end

end
